### ISSUE TITLE
release 1.2.0?

### ISSUE THREAD

**Issue by polettif** [r-transit/gtfsio#39]
With the changes in #37 and the pending updates in tidytransit we should push a new release of `gtfsio`. Version `1.2.0` seems appropriate to me. Could you initiate that, @dhersz?

I think we'll leave #38 to a later release, @mpadge?

**Comment by mpadge** [comment]
Thanks @polettif! I'd be able to find time this week to convert all file calls to `fs` versions for this release if that would help?

**Comment by polettif** [comment]
> Thanks @polettif! I'd be able to find time this week to convert all file calls to `fs` versions for this release if that would help?

Yes, that would be great!

**Comment by mpadge** [comment]
@dhersz @polettif I've pinged you both as reviewers for #40. I also note that [`NEWS.md`](https://github.com/r-transit/gtfsio/blob/master/NEWS.md) hasn't been updated at all, and that definitely should be done prior to release. Thanks!

**Comment by mpadge** [comment]
And BTW Daniel, congrats on new job and new city! Great to hear!

**Comment by polettif** [comment]
I think we're ready to go @dhersz. I just pushed an update to the news file, please change/edit as you see fit.

**Comment by dhersz** [comment]
Cool, thanks! Will make one last revision and submit it.

**Comment by dhersz** [comment]
Done. Thank you guys for all the work you've put into this release!
