### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by dhersz** [r-transit/gtfsio#8]
I have created a `pkgdown` GitHub Actions to deploy a GitHub Page from the `gh-pages` branch, but the website created by GitHub is not working: https://www.r-transit.org/gtfsio/.

This is probably a `r-transit` domain issue (not sure if I'd even call it a issue, but anyway), as `{tidytransit}`'s website works fine. 

Perhaps either @polettif or @tbuckl could take a look at this?

**Comment by mpadge** [comment]
@dhersz go to `Settings`, and scroll down on the first page to switch on github pages, and set the branch to `gh-pages`. See also [`usethis::use_pkgdown()`](https://usethis.r-lib.org/reference/use_pkgdown.html) for more info. Hope that helps!

**Comment by dhersz** [comment]
I had done that already, but GitHub was publishing the website at the URL I posted above.

I just went to check if I had messed something up and...

>  Your site is published at https://r-transit.github.io/gtfsio/

The URL changed? I don't know what happened, but I'm happy with it. It works now! https://r-transit.github.io/gtfsio/

**Comment by mpadge** [comment]
Yeah, a first set-up sometimes takes a few (tens of) minutes for github to deploy. Great that it's there!
