### ISSUE TITLE
unused params in new_gtfs

### ISSUE THREAD

**Issue by polettif** [r-transit/gtfsio#9]
[import_gtfs.R#L174](https://github.com/r-transit/gtfsio/blob/94a148edac8862eecd3f728ca76fa3e14cfa18ca/R/import_gtfs.R#L174) uses `new_gtfs(gtfs, names = files_to_read)` which isn't used in new_gtfs. What's the intended behaviour?

**Comment by dhersz** [comment]
Nice catach @polettif. I used to use this argument to assign names to the GTFS, but then I decided to do that explicitly a few lines above. Apparently I forgot to remove it from the call.
